layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

timezone: America/New_York

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: dung.nguyenhophuong
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: dzungng
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://dzungpng.github.io
  # youtube: your_username

# interest topics
topics:
  - name: Rendering
    web_url: https://github.com/topics/physically-based-rendering
    image_url: /images/rendering.png

  - name: Virtual Reality
    web_url: https://github.com/topics/virtual-reality
    image_url: /images/vr.png

  - name: Neural Networks
    web_url: https://github.com/topics/neural-network
    image_url: /images/ai.png

# portfolio topics
pitems:
  - name: Computer Graphics
    web_url: http://dzungpng.github.io/cgprojects
    image_url: /images/cg.png

  - name: Web Development
    web_url: http://dzungpng.github.io/webprojects
    image_url: /images/webdev.jpeg

  - name: Miscellaneous
    web_url: http://dzungpng.github.io/miscprojects
    image_url: /images/misc.png
