layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

timezone: America/New_York

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  sort_by options:
    - pushed
    # - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: dung.nguyenhophuong
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: dzungng
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://dzungpng.github.io
  # youtube: your_username

# Me!
topics:
  - name: Penn Computer Graphics Student
    web_url: http://cg.cis.upenn.edu/
    image_url: /images/penn.jpg

  - name: Jack Kent Cooke Foundation Scholar
    web_url: https://www.jkcf.org/
    image_url: /images/jkc.jpg

  - name: Rewriting the Code Fellow
    web_url: https://rewritingthecode.org/
    image_url: /images/RTC.jpg

  - name: CBRE Build Software Engineer Intern
    web_url: https://www.cbrebuild.com/
    image_url: /images/cbre-build.png

  - name: Penn SIGGRAPH External Relations Chair
    web_url: http://cg.cis.upenn.edu/siggraph/main.html#chapter
    image_url: /images/siggraph.png

  - name: Proud Artist Since I was Four
    web_url: pages/aboutme-art
    image_url: /images/artist.jpg

# portfolio topics
pitems:
  - name: Monte Carlo Pathtracer
    web_url: /pages/monte-carlo
    image_url: /images/mt-4.png

  - name: 3D Mesh Editor
    web_url: /pages/mesh-editor
    image_url: /images/beach_ball.png

  - name: Japanese-ink Minecraft
    web_url: /pages/minecraft
    image_url: /images/minecraft.png

  - name: OpenGL Shaders
    web_url: /pages/shaders
    image_url: /images/shader.png

  - name: Deal IQ
    web_url: /pages/web-dealiq
    image_url: /images/deal_logo.png

  - name: PennCourseRec
    web_url: /pages/web-penncourserec
    image_url: /images/calendar.png

  - name: Boba Sweeper
    web_url: https://vimeo.com/348311559
    image_url: /images/bobasweeper.png

  - name: careermatch
    web_url: https://github.com/rguan1/CareerJetRecommender
    image_url: /images/careermatch.png

  - name: WeathAR
    web_url: https://devpost.com/software/weathar-visualizing-forecasts-and-natural-disasters
    image_url: /images/weathar.png

  - name: U-Net Waveform Segmentation 
    web_url: https://github.com/dzungpng/wave-extraction-unet
    image_url: /images/waves.png
