layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

timezone: America/New_York

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: dung.nguyenhophuong
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: dzungng
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  website: http://dzungpng.github.io
  # youtube: your_username

# interest topics
topics:
  - name: Rendering
    web_url: https://github.com/topics/physically-based-rendering
    image_url: /images/rendering.png

  - name: Virtual Reality
    web_url: https://github.com/topics/virtual-reality
    image_url: /images/vr.png

  - name: Neural Networks
    web_url: https://github.com/topics/neural-network
    image_url: /images/ai.png

# portfolio topics
pitems:
  - name: Computer Graphics
    web_url: http://dzungpng.github.io/cgprojects
    image_url: /images/cg.png

  - name: Web Development
    web_url: http://dzungpng.github.io/webprojects
    image_url: /images/webdev.jpeg

  - name: Miscellaneous
    web_url: http://dzungpng.github.io/miscprojects
    image_url: /images/misc.png

# cg projects
cgprojects:
  - name: Monte Carlo Pathtracer
    web_url: http://dzungpng.github.io/pages/monte-carlo
    image_url: /images/mt-4.png

  - name: 3D Mesh Editor
    web_url: http://dzungpng.github.io/pages/mesh-editor
    image_url: /images/beach_ball.png

  - name: Japanese-ink Minecraft
    web_url: http://dzungpng.github.io/pages/minecraft
    image_url: /images/minecraft.png

  - name: OpenGL Shaders
    web_url: http://dzungpng.github.io/pages/shaders
    image_url: /images/shader.png

# misc projects
miscprojects:
  - name: BobaSweeper
    web_url: https://github.com/topics/physically-based-rendering
    image_url: /images/rendering.png

  - name: careermatch
    web_url: https://github.com/topics/virtual-reality
    image_url: /images/vr.png

  - name: WeathAR
    web_url: https://github.com/topics/neural-network
    image_url: /images/ai.png

  - name: Cardiac Waveform Segmentation with u-net
    web_url: https://github.com/topics/neural-network
    image_url: /images/ai.png

  - name: 2D Art
    web_url: https://github.com/topics/neural-network
    image_url: /images/ai.png

  - name: 3D Art
    web_url: https://github.com/topics/neural-network
    image_url: /images/ai.png

# web projects
webprojects:
  - name: Deal IQ
    web_url: https://github.com/topics/physically-based-rendering
    image_url: /images/rendering.png

  - name: PennCourseRec
    web_url: https://github.com/topics/virtual-reality
    image_url: /images/vr.png

  - name: Scrum Board API
    web_url: https://github.com/topics/neural-network
    image_url: /images/ai.png